In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd

In [2]:
tf.__version__

'2.3.0'

# **SeoulBikeData (Dataset_1)**

### **Data Processing**

In [3]:
dataset = pd.read_csv("/content/SeoulBikeData.csv",encoding='latin1') 
dataset.head(3) # view the data
# dataset.dtypes

Date  Rented Bike Count  Hour  ...  Seasons     Holiday  Functioning Day
0  01/12/2017                254     0  ...   Winter  No Holiday              Yes
1  01/12/2017                204     1  ...   Winter  No Holiday              Yes
2  01/12/2017                173     2  ...   Winter  No Holiday              Yes

[3 rows x 14 columns]

In [4]:
X = dataset.iloc[:, 2:-1].values #Drop data
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[0 -5.2 37 ... 0.0 'Winter' 'No Holiday']
 [1 -5.5 38 ... 0.0 'Winter' 'No Holiday']
 [2 -6.0 39 ... 0.0 'Winter' 'No Holiday']
 ...
 [21 2.6 39 ... 0.0 'Autumn' 'No Holiday']
 [22 2.1 41 ... 0.0 'Autumn' 'No Holiday']
 [23 1.9 43 ... 0.0 'Autumn' 'No Holiday']]


In [6]:
print(y)

['Yes' 'Yes' 'Yes' ... 'Yes' 'Yes' 'Yes']


Encoding the Independent Variable

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1,-2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X[0,:]) # 15 Variables

[0.0 1.0 0.0 0.0 0.0 1.0 0 -5.2 37 2.2 2000 -17.6 0.0 0.0 0.0]


Encoding the Dependent Variable

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
import collections
collections.Counter(y)

Counter({0: 295, 1: 8465})

Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [12]:
print(y_train.shape, X_train.shape, y_test.shape, X_test.shape)

(6132,) (6132, 15) (2628,) (2628, 15)


Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# ready X_train, X_test, y_train, y_test

##**Artificial neural networks (ANN)**

### **Building the Ann with 2 hidden layers 4 & 6 Units 100 & 300 epochs**

 **Initializing the ANN
(2 hidden layer, 6 unite, activation='relu', output activation='sigmoid')**

In [14]:
ann_2_6 = tf.keras.models.Sequential()
ann_2_6.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann_2_6.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann_2_6.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

(2 hidden layer, 4 unite, activation='relu', output activation='sigmoid')

In [15]:
ann_2_4 = tf.keras.models.Sequential()
ann_2_4.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann_2_4.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann_2_4.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#### **ANN 2 hidden layers 6 units "Adam" epochs 100**

Compiling the ANN

In [16]:
ann_2_6.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [17]:
ann_2_6.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
192/192 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.9056
Epoch 2/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1576 - accuracy: 0.9677
Epoch 3/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1275 - accuracy: 0.9677
Epoch 4/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1200 - accuracy: 0.9677
Epoch 5/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1153 - accuracy: 0.9677
Epoch 6/100
192/192 [==============================] - 0s 2ms/step - loss: 0.1117 - accuracy: 0.9677
Epoch 7/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1089 - accuracy: 0.9677
Epoch 8/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1067 - accuracy: 0.9677
Epoch 9/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1051 - accuracy: 0.9677
Epoch 10/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1035 - accura

Training set results and Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  17  181]
 [   9 5925]]
Accuracy: 96.90 %


Test set Predition & Confusion Matrix

In [19]:
y_pred = ann_2_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   7   90]
 [   3 2528]]
Accuracy: 96.46 %


#### **ANN 2 hidden layers 6 units "Adam" epochs 300**

---



Training the Training set

In [20]:
ann_2_6.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0794 - accuracy: 0.9685
Epoch 2/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0792 - accuracy: 0.9677
Epoch 3/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0793 - accuracy: 0.9687
Epoch 4/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0794 - accuracy: 0.9685
Epoch 5/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0788 - accuracy: 0.9692
Epoch 6/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0790 - accuracy: 0.9682
Epoch 7/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0790 - accuracy: 0.9687
Epoch 8/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0789 - accuracy: 0.9669
Epoch 9/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0788 - accuracy: 0.9684
Epoch 10/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0789 - accura

Training set results and Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  37  161]
 [  20 5914]]
Accuracy: 97.05 %


Test set Predition & Confusion Matrix

In [22]:
y_pred = ann_2_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[  16   81]
 [  10 2521]]
Accuracy: 96.54 %


#### **ANN 2 hidden layers 6 units "SGD" epochs 100**

Compiling the ANN

In [23]:
ann_2_6.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [24]:
ann_2_6.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
192/192 [==============================] - 0s 962us/step - loss: 0.0699 - accuracy: 0.9698
Epoch 2/100
192/192 [==============================] - 0s 875us/step - loss: 0.0700 - accuracy: 0.9695
Epoch 3/100
192/192 [==============================] - 0s 871us/step - loss: 0.0696 - accuracy: 0.9693
Epoch 4/100
192/192 [==============================] - 0s 875us/step - loss: 0.0698 - accuracy: 0.9702
Epoch 5/100
192/192 [==============================] - 0s 861us/step - loss: 0.0698 - accuracy: 0.9695
Epoch 6/100
192/192 [==============================] - 0s 958us/step - loss: 0.0692 - accuracy: 0.9703
Epoch 7/100
192/192 [==============================] - 0s 907us/step - loss: 0.0698 - accuracy: 0.9695
Epoch 8/100
192/192 [==============================] - 0s 926us/step - loss: 0.0698 - accuracy: 0.9689
Epoch 9/100
192/192 [==============================] - 0s 953us/step - loss: 0.0698 - accuracy: 0.9695
Epoch 10/100
192/192 [==============================] - 0s 902us/step - l

Training set results and Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  45  153]
 [  31 5903]]
Accuracy: 97.00 %


Test set Predition & Confusion Matrix

In [26]:
y_pred = ann_2_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[  16   81]
 [  18 2513]]
Accuracy: 96.23 %


#### **ANN 2 hidden layers 6 units "SGD" epochs 300**

Training the Training set

In [27]:
ann_2_6.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
192/192 [==============================] - 0s 986us/step - loss: 0.0693 - accuracy: 0.9703
Epoch 2/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0695 - accuracy: 0.9710
Epoch 3/300
192/192 [==============================] - 0s 975us/step - loss: 0.0694 - accuracy: 0.9705
Epoch 4/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0696 - accuracy: 0.9693
Epoch 5/300
192/192 [==============================] - 0s 994us/step - loss: 0.0691 - accuracy: 0.9698
Epoch 6/300
192/192 [==============================] - 0s 927us/step - loss: 0.0692 - accuracy: 0.9698
Epoch 7/300
192/192 [==============================] - 0s 965us/step - loss: 0.0695 - accuracy: 0.9703
Epoch 8/300
192/192 [==============================] - 0s 968us/step - loss: 0.0695 - accuracy: 0.9689
Epoch 9/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0692 - accuracy: 0.9703
Epoch 10/300
192/192 [==============================] - 0s 928us/step - loss: 0

Training set results and Confusion Matrix

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  54  144]
 [  32 5902]]
Accuracy: 97.13 %


Test set Predition & Confusion Matrix

In [29]:
y_pred = ann_2_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[  17   80]
 [  19 2512]]
Accuracy: 96.23 %


#### **ANN 2 hidden layers 4 units "Adam" epochs 100**

Compiling the ANN

In [30]:
ann_2_4.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [31]:
ann_2_4.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
192/192 [==============================] - 0s 1ms/step - loss: 0.6311 - accuracy: 0.7451
Epoch 2/100
192/192 [==============================] - 0s 991us/step - loss: 0.3924 - accuracy: 0.9609
Epoch 3/100
192/192 [==============================] - 0s 943us/step - loss: 0.2703 - accuracy: 0.9672
Epoch 4/100
192/192 [==============================] - 0s 964us/step - loss: 0.1452 - accuracy: 0.9677
Epoch 5/100
192/192 [==============================] - 0s 908us/step - loss: 0.1181 - accuracy: 0.9677
Epoch 6/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1118 - accuracy: 0.9677
Epoch 7/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1094 - accuracy: 0.9677
Epoch 8/100
192/192 [==============================] - 0s 988us/step - loss: 0.1077 - accuracy: 0.9677
Epoch 9/100
192/192 [==============================] - 0s 973us/step - loss: 0.1064 - accuracy: 0.9677
Epoch 10/100
192/192 [==============================] - 0s 983us/step - loss: 0

Training set results and Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[   3  195]
 [   0 5934]]
Accuracy: 96.82 %


Test set Predition & Confusion Matrix

In [33]:
y_pred = ann_2_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   1   96]
 [   0 2531]]
Accuracy: 96.35 %


#### **ANN 2 hidden layers 4 units "Adam" epochs 300**

Training the Training set

In [34]:
ann_2_4.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0889 - accuracy: 0.9684
Epoch 2/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0887 - accuracy: 0.9687
Epoch 3/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0890 - accuracy: 0.9685
Epoch 4/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0885 - accuracy: 0.9690
Epoch 5/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0884 - accuracy: 0.9690
Epoch 6/300
192/192 [==============================] - 0s 966us/step - loss: 0.0885 - accuracy: 0.9687
Epoch 7/300
192/192 [==============================] - 0s 956us/step - loss: 0.0884 - accuracy: 0.9684
Epoch 8/300
192/192 [==============================] - 0s 997us/step - loss: 0.0884 - accuracy: 0.9684
Epoch 9/300
192/192 [==============================] - 0s 933us/step - loss: 0.0883 - accuracy: 0.9687
Epoch 10/300
192/192 [==============================] - 0s 960us/step - loss: 0.088

Training set results and Confusion Matrix

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  16  182]
 [   2 5932]]
Accuracy: 97.00 %


Test set Predition & Confusion Matrix

In [36]:
y_pred = ann_2_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   3   94]
 [   3 2528]]
Accuracy: 96.31 %


#### **ANN 2 hidden layers 4 units "SGD" epochs 100**

Compiling the ANN

In [37]:
ann_2_4.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [38]:
ann_2_4.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
192/192 [==============================] - 0s 918us/step - loss: 0.0794 - accuracy: 0.9715
Epoch 2/100
192/192 [==============================] - 0s 937us/step - loss: 0.0788 - accuracy: 0.9724
Epoch 3/100
192/192 [==============================] - 0s 1ms/step - loss: 0.0792 - accuracy: 0.9715
Epoch 4/100
192/192 [==============================] - 0s 963us/step - loss: 0.0791 - accuracy: 0.9718
Epoch 5/100
192/192 [==============================] - 0s 889us/step - loss: 0.0789 - accuracy: 0.9718
Epoch 6/100
192/192 [==============================] - 0s 918us/step - loss: 0.0791 - accuracy: 0.9715
Epoch 7/100
192/192 [==============================] - 0s 927us/step - loss: 0.0788 - accuracy: 0.9715
Epoch 8/100
192/192 [==============================] - 0s 887us/step - loss: 0.0786 - accuracy: 0.9718
Epoch 9/100
192/192 [==============================] - 0s 900us/step - loss: 0.0790 - accuracy: 0.9721
Epoch 10/100
192/192 [==============================] - 0s 909us/step - los

Training set results and Confusion Matrix

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  26  172]
 [   5 5929]]
Accuracy: 97.11 %


Test set Predition & Confusion Matrix

In [40]:
y_pred = ann_2_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   3   94]
 [   5 2526]]
Accuracy: 96.23 %


#### **ANN 2 hidden layers 4 units "SGD" epochs 300**

Training the Training set

In [41]:
ann_2_4.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
192/192 [==============================] - 0s 944us/step - loss: 0.0786 - accuracy: 0.9723
Epoch 2/300
192/192 [==============================] - 0s 942us/step - loss: 0.0786 - accuracy: 0.9715
Epoch 3/300
192/192 [==============================] - 0s 939us/step - loss: 0.0786 - accuracy: 0.9724
Epoch 4/300
192/192 [==============================] - 0s 894us/step - loss: 0.0786 - accuracy: 0.9715
Epoch 5/300
192/192 [==============================] - 0s 983us/step - loss: 0.0787 - accuracy: 0.9716
Epoch 6/300
192/192 [==============================] - 0s 979us/step - loss: 0.0785 - accuracy: 0.9723
Epoch 7/300
192/192 [==============================] - 0s 911us/step - loss: 0.0786 - accuracy: 0.9723
Epoch 8/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0783 - accuracy: 0.9713
Epoch 9/300
192/192 [==============================] - 0s 913us/step - loss: 0.0788 - accuracy: 0.9721
Epoch 10/300
192/192 [==============================] - 0s 916us/step - los

Training set results and Confusion Matrix

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  39  159]
 [  10 5924]]
Accuracy: 97.24 %


Test set Predition & Confusion Matrix

In [43]:
y_pred = ann_2_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   9   88]
 [   8 2523]]
Accuracy: 96.35 %


### **Building the Ann with 1 hidden layers, 4 & 6 Units, 100 & 300 epochs**

 **Initializing the ANN
(1 hidden layer, 6 unite, activation='relu', output activation='sigmoid')**

In [44]:
ann_1_6 = tf.keras.models.Sequential()
ann_1_6.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann_1_6.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

(2 hidden layer, 4 unite, activation='relu', output activation='sigmoid')

In [45]:
ann_1_4 = tf.keras.models.Sequential()
ann_1_4.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann_1_4.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#### **ANN 1 hidden layers 6 units "Adam" epochs 100**

Compiling the ANN

In [46]:
ann_1_6.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [47]:
ann_1_6.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
192/192 [==============================] - 0s 1ms/step - loss: 0.4224 - accuracy: 0.8513
Epoch 2/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1953 - accuracy: 0.9640
Epoch 3/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1384 - accuracy: 0.9672
Epoch 4/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1206 - accuracy: 0.9674
Epoch 5/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1135 - accuracy: 0.9675
Epoch 6/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1095 - accuracy: 0.9675
Epoch 7/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1070 - accuracy: 0.9675
Epoch 8/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1054 - accuracy: 0.9677
Epoch 9/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1042 - accuracy: 0.9677
Epoch 10/100
192/192 [==============================] - 0s 1ms/step - loss: 0.1032 - accura

Training set results and Confusion Matrix

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  20  178]
 [   2 5932]]
Accuracy: 97.06 %


Test set Predition & Confusion Matrix

In [49]:
y_pred = ann_1_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   2   95]
 [   2 2529]]
Accuracy: 96.31 %


#### **ANN 1 hidden layers 6 units "Adam" epochs 300**

Training the Training set

In [50]:
ann_1_6.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0854 - accuracy: 0.9705
Epoch 2/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0854 - accuracy: 0.9695
Epoch 3/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0854 - accuracy: 0.9700
Epoch 4/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0855 - accuracy: 0.9698
Epoch 5/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0854 - accuracy: 0.9700
Epoch 6/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0852 - accuracy: 0.9697
Epoch 7/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0853 - accuracy: 0.9702
Epoch 8/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0851 - accuracy: 0.9695
Epoch 9/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0850 - accuracy: 0.9695
Epoch 10/300
192/192 [==============================] - 0s 2ms/step - loss: 0.0848 - accura

Training set results and Confusion Matrix

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  37  161]
 [  12 5922]]
Accuracy: 97.18 %


Test set Predition & Confusion Matrix

In [52]:
y_pred = ann_1_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   7   90]
 [   9 2522]]
Accuracy: 96.23 %


#### **ANN 1 hidden layers 6 units "SGD" epochs 100**

Compiling the ANN

In [53]:
ann_1_6.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [54]:
ann_1_6.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
192/192 [==============================] - 0s 1ms/step - loss: 0.0728 - accuracy: 0.9720
Epoch 2/100
192/192 [==============================] - 0s 973us/step - loss: 0.0728 - accuracy: 0.9723
Epoch 3/100
192/192 [==============================] - 0s 1ms/step - loss: 0.0728 - accuracy: 0.9710
Epoch 4/100
192/192 [==============================] - 0s 987us/step - loss: 0.0728 - accuracy: 0.9711
Epoch 5/100
192/192 [==============================] - 0s 965us/step - loss: 0.0729 - accuracy: 0.9713
Epoch 6/100
192/192 [==============================] - 0s 1ms/step - loss: 0.0728 - accuracy: 0.9718
Epoch 7/100
192/192 [==============================] - 0s 939us/step - loss: 0.0727 - accuracy: 0.9711
Epoch 8/100
192/192 [==============================] - 0s 1ms/step - loss: 0.0729 - accuracy: 0.9708
Epoch 9/100
192/192 [==============================] - 0s 889us/step - loss: 0.0728 - accuracy: 0.9716
Epoch 10/100
192/192 [==============================] - 0s 906us/step - loss: 0.0

Training set results and Confusion Matrix

In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  39  159]
 [  13 5921]]
Accuracy: 97.20 %


Test set Predition & Confusion Matrix

In [56]:
y_pred = ann_1_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   9   88]
 [  10 2521]]
Accuracy: 96.27 %


#### **ANN 1 hidden layers 6 units "SGD" epochs 300**

Training the Training set

In [57]:
ann_1_6.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0726 - accuracy: 0.9724
Epoch 2/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0726 - accuracy: 0.9718
Epoch 3/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0726 - accuracy: 0.9713
Epoch 4/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0727 - accuracy: 0.9715
Epoch 5/300
192/192 [==============================] - 0s 895us/step - loss: 0.0723 - accuracy: 0.9720
Epoch 6/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0726 - accuracy: 0.9713
Epoch 7/300
192/192 [==============================] - 0s 912us/step - loss: 0.0725 - accuracy: 0.9716
Epoch 8/300
192/192 [==============================] - 0s 916us/step - loss: 0.0725 - accuracy: 0.9721
Epoch 9/300
192/192 [==============================] - 0s 949us/step - loss: 0.0726 - accuracy: 0.9718
Epoch 10/300
192/192 [==============================] - 0s 960us/step - loss: 0.072

Training set results and Confusion Matrix

In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[  56  142]
 [  29 5905]]
Accuracy: 97.21 %


Test set Predition & Confusion Matrix

In [59]:
y_pred = ann_1_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[  14   83]
 [  17 2514]]
Accuracy: 96.19 %


#### **ANN 1 hidden layers 4 units "Adam" epochs 100**

Compiling the ANN

In [60]:
ann_1_4.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [61]:
ann_1_4.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
192/192 [==============================] - 0s 985us/step - loss: 0.7568 - accuracy: 0.5801
Epoch 2/100
192/192 [==============================] - 0s 979us/step - loss: 0.3871 - accuracy: 0.8935
Epoch 3/100
192/192 [==============================] - 0s 920us/step - loss: 0.2420 - accuracy: 0.9614
Epoch 4/100
192/192 [==============================] - 0s 946us/step - loss: 0.1839 - accuracy: 0.9669
Epoch 5/100
192/192 [==============================] - 0s 942us/step - loss: 0.1583 - accuracy: 0.9675
Epoch 6/100
192/192 [==============================] - 0s 896us/step - loss: 0.1459 - accuracy: 0.9677
Epoch 7/100
192/192 [==============================] - 0s 958us/step - loss: 0.1391 - accuracy: 0.9677
Epoch 8/100
192/192 [==============================] - 0s 957us/step - loss: 0.1347 - accuracy: 0.9677
Epoch 9/100
192/192 [==============================] - 0s 943us/step - loss: 0.1315 - accuracy: 0.9677
Epoch 10/100
192/192 [==============================] - 0s 931us/step - l

Training set results and Confusion Matrix

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[   0  198]
 [   0 5934]]
Accuracy: 96.77 %


Test set Predition & Confusion Matrix

In [63]:
y_pred = ann_1_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   0   97]
 [   0 2531]]
Accuracy: 96.31 %


#### **ANN 1 hidden layers 4 units "Adam" epochs 300**

Training the Training set

In [64]:
ann_1_4.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
192/192 [==============================] - 0s 953us/step - loss: 0.1017 - accuracy: 0.9677
Epoch 2/300
192/192 [==============================] - 0s 1ms/step - loss: 0.1018 - accuracy: 0.9677
Epoch 3/300
192/192 [==============================] - 0s 938us/step - loss: 0.1017 - accuracy: 0.9677
Epoch 4/300
192/192 [==============================] - 0s 923us/step - loss: 0.1016 - accuracy: 0.9677
Epoch 5/300
192/192 [==============================] - 0s 1ms/step - loss: 0.1017 - accuracy: 0.9677
Epoch 6/300
192/192 [==============================] - 0s 924us/step - loss: 0.1015 - accuracy: 0.9677
Epoch 7/300
192/192 [==============================] - 0s 907us/step - loss: 0.1017 - accuracy: 0.9677
Epoch 8/300
192/192 [==============================] - 0s 981us/step - loss: 0.1015 - accuracy: 0.9677
Epoch 9/300
192/192 [==============================] - 0s 907us/step - loss: 0.1016 - accuracy: 0.9677
Epoch 10/300
192/192 [==============================] - 0s 931us/step - loss:

Training set results and Confusion Matrix

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[   4  194]
 [   7 5927]]
Accuracy: 96.72 %


Test set Predition & Confusion Matrix

In [66]:
y_pred = ann_1_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   0   97]
 [  12 2519]]
Accuracy: 95.85 %


#### **ANN 1 hidden layers 4 units "SGD" epochs 100**

Compiling the ANN

In [67]:
ann_1_4.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [68]:
ann_1_4.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
192/192 [==============================] - 0s 938us/step - loss: 0.0966 - accuracy: 0.9674
Epoch 2/100
192/192 [==============================] - 0s 918us/step - loss: 0.0965 - accuracy: 0.9680
Epoch 3/100
192/192 [==============================] - 0s 906us/step - loss: 0.0965 - accuracy: 0.9680
Epoch 4/100
192/192 [==============================] - 0s 883us/step - loss: 0.0965 - accuracy: 0.9677
Epoch 5/100
192/192 [==============================] - 0s 895us/step - loss: 0.0965 - accuracy: 0.9680
Epoch 6/100
192/192 [==============================] - 0s 1ms/step - loss: 0.0965 - accuracy: 0.9677
Epoch 7/100
192/192 [==============================] - 0s 983us/step - loss: 0.0965 - accuracy: 0.9677
Epoch 8/100
192/192 [==============================] - 0s 949us/step - loss: 0.0965 - accuracy: 0.9679
Epoch 9/100
192/192 [==============================] - 0s 898us/step - loss: 0.0965 - accuracy: 0.9677
Epoch 10/100
192/192 [==============================] - 0s 932us/step - los

Training set results and Confusion Matrix

In [69]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[   5  193]
 [   2 5932]]
Accuracy: 96.82 %


Test set Predition & Confusion Matrix

In [70]:
y_pred = ann_1_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   0   97]
 [   7 2524]]
Accuracy: 96.04 %


#### **ANN 1 hidden layers 4 units "SGD" epochs 300**

Training the Training set

In [71]:
ann_1_4.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
192/192 [==============================] - 0s 945us/step - loss: 0.0963 - accuracy: 0.9682
Epoch 2/300
192/192 [==============================] - 0s 945us/step - loss: 0.0963 - accuracy: 0.9679
Epoch 3/300
192/192 [==============================] - 0s 957us/step - loss: 0.0963 - accuracy: 0.9680
Epoch 4/300
192/192 [==============================] - 0s 953us/step - loss: 0.0963 - accuracy: 0.9679
Epoch 5/300
192/192 [==============================] - 0s 918us/step - loss: 0.0963 - accuracy: 0.9677
Epoch 6/300
192/192 [==============================] - 0s 1ms/step - loss: 0.0963 - accuracy: 0.9680
Epoch 7/300
192/192 [==============================] - 0s 900us/step - loss: 0.0964 - accuracy: 0.9675
Epoch 8/300
192/192 [==============================] - 0s 877us/step - loss: 0.0963 - accuracy: 0.9680
Epoch 9/300
192/192 [==============================] - 0s 941us/step - loss: 0.0963 - accuracy: 0.9679
Epoch 10/300
192/192 [==============================] - 0s 945us/step - los

Training set results and Confusion Matrix

In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[   8  190]
 [   3 5931]]
Accuracy: 96.85 %


Test set Predition & Confusion Matrix

In [73]:
y_pred = ann_1_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   1   96]
 [   7 2524]]
Accuracy: 96.08 %


##**K Nearest Neighbors**

### **3 neighbors & metric = 'minkowski'**

In [74]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [75]:
y_pred_K_in = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred_K_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred_K_in)*100))

[[  36   61]
 [  26 2505]]
Accuracy: 96.69 %


In [76]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.61 %
Standard Deviation: 0.55 %


In [77]:
y_pred_K = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Standard Deviation: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   1   96]
 [   7 2524]]
Standard Deviation: 96.08 %


### **10 neighbors & metric = 'minkowski'**

In [78]:
classifier = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [79]:
y_pred_K_in = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred_K_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred_K_in)*100))

[[  13   84]
 [  13 2518]]
Accuracy: 96.31 %


In [80]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 97.00 %
Standard Deviation: 0.22 %


In [81]:
y_pred_K = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Standard Deviation: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   1   96]
 [   7 2524]]
Standard Deviation: 96.08 %


### **3 neighbors & metric = 'euclidean'**

In [82]:
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [83]:
y_pred_K_in = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred_K_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred_K_in)*100))

[[  36   61]
 [  26 2505]]
Accuracy: 96.69 %


In [84]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.61 %
Standard Deviation: 0.55 %


In [85]:
y_pred_K = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Standard Deviation: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   1   96]
 [   7 2524]]
Standard Deviation: 96.08 %


### **10 neighbors & metric = 'euclidean'**

In [86]:
classifier = KNeighborsClassifier(n_neighbors = 10, metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [87]:
y_pred_K_in = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred_K_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred_K_in)*100))

[[  13   84]
 [  13 2518]]
Accuracy: 96.31 %


In [88]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 97.00 %
Standard Deviation: 0.22 %


In [89]:
y_pred_K = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Standard Deviation: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[   1   96]
 [   7 2524]]
Standard Deviation: 96.08 %


# **IBM HR Dataset Processing**

### **Data Processing**

In [90]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
import collections, numpy
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.preprocessing import OrdinalEncoder

In [91]:
dataset = pd.read_csv("/content/WA_Fn-UseC_-HR-Employee-Attrition.csv") 
dataset.head(3) # view the data
# dataset.dtypes


Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0   41       Yes  ...                       0                     5
1   49        No  ...                       1                     7
2   37       Yes  ...                       0                     0

[3 rows x 35 columns]

In [92]:
# dataset.isnull().sum() # check the Missing Data

In [93]:
# dataset.dtypes #PerformanceRating

In [94]:
dataset = dataset.drop(['PercentSalaryHike'], axis=1) 
dataset.head(3) # view the data

Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0   41       Yes  ...                       0                     5
1   49        No  ...                       1                     7
2   37       Yes  ...                       0                     0

[3 rows x 34 columns]

In [95]:
PerformanceRating = dataset['PerformanceRating']
dataset.drop(labels=['PerformanceRating'], axis=1, inplace = True)
dataset.insert(0, 'PerformanceRating', PerformanceRating)
dataset.head(3)

PerformanceRating  Age  ... YearsSinceLastPromotion YearsWithCurrManager
0                  3   41  ...                       0                    5
1                  4   49  ...                       1                    7
2                  3   37  ...                       0                    0

[3 rows x 34 columns]

In [96]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

In [97]:
print(X[0])
print(y)

[41 'Yes' 'Travel_Rarely' 1102 'Sales' 1 2 'Life Sciences' 1 1 2 'Female'
 94 3 2 'Sales Executive' 4 'Single' 5993 19479 8 'Y' 'Yes' 1 80 0 8 0 1 6
 4 0 5]
[3 4 3 ... 4 3 3]


In [98]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,4,7,11,15,21,22,17])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X[0])

[0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 41 1102 1 2 1 1 2 94
 3 2 4 5993 19479 8 1 80 0 8 0 1 6 4 0 5]


Encoding the Dependent Variable

In [99]:
le = LabelEncoder()
y = le.fit_transform(y)
print(collections.Counter(y)) # 3 is 1244(0), 4 is 226(1), check whether is binary classification.
print(y)

Counter({0: 1244, 1: 226})
[0 1 0 ... 1 0 0]


In [100]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1029, 55) (441, 55) (1029,) (441,)


In [101]:
X_train = np.asarray(X_train).astype('float32')
y_train = np.asarray(y_train).astype('float32')
X_test = np.asarray(X_test).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [102]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# ready X_train, X_test, y_train, y_test

##**Artificial neural networks (ANN)**

### **Building the Ann with 2 hidden layers 4 & 6 Units 100 & 300 epochs**

 **Initializing the ANN
(2 hidden layer, 6 unite, activation='relu', output activation='sigmoid')**

In [103]:
ann_2_6_ibm = tf.keras.models.Sequential()
ann_2_6_ibm.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann_2_6_ibm.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann_2_6_ibm.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

(2 hidden layer, 4 unite, activation='relu', output activation='sigmoid')

In [104]:
ann_2_4_ibm = tf.keras.models.Sequential()
ann_2_4_ibm.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann_2_4_ibm.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann_2_4_ibm.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#### **ANN 2 hidden layers 6 units "Adam" epochs 100**

Compiling the ANN

In [105]:
ann_2_6_ibm.compile(optimizer ='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [106]:
ann_2_6_ibm.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
33/33 [==============================] - 0s 1ms/step - loss: 0.6196 - accuracy: 0.6657
Epoch 2/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5569 - accuracy: 0.7396
Epoch 3/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5156 - accuracy: 0.7852
Epoch 4/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4871 - accuracy: 0.8154
Epoch 5/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4691 - accuracy: 0.8270
Epoch 6/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4567 - accuracy: 0.8319
Epoch 7/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4476 - accuracy: 0.8387
Epoch 8/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4402 - accuracy: 0.8416
Epoch 9/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4346 - accuracy: 0.8435
Epoch 10/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4297 - accuracy: 0.8435
Epoch 11/

Training set results and Confusion Matrix

In [107]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_6_ibm.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[863   7]
 [117  42]]
Accuracy: 87.95 %


Test set Predition & Confusion Matrix

In [108]:
y_pred = ann_2_6_ibm.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[360  14]
 [ 63   4]]
Accuracy: 82.54 %


#### **ANN 2 hidden layers 6 units "Adam" epochs 300**

---



Compiling the ANN

In [109]:
ann_2_6_ibm.compile(optimizer ='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [110]:
ann_2_6_ibm.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2976 - accuracy: 0.8805
Epoch 2/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2938 - accuracy: 0.8756
Epoch 3/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2938 - accuracy: 0.8776
Epoch 4/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2935 - accuracy: 0.8766
Epoch 5/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2915 - accuracy: 0.8766
Epoch 6/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2908 - accuracy: 0.8756
Epoch 7/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2904 - accuracy: 0.8766
Epoch 8/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2888 - accuracy: 0.8785
Epoch 9/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2888 - accuracy: 0.8795
Epoch 10/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2867 - accuracy: 0.8814
Epoch 11/

Training set results and Confusion Matrix

In [111]:
y_pred_in = ann_2_6_ibm.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[847  23]
 [ 65  94]]
Accuracy: 91.45 %


Test set Predition & Confusion Matrix

In [112]:
y_pred = ann_2_6_ibm.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[330  44]
 [ 57  10]]
Accuracy: 77.10 %


#### **ANN 2 hidden layers 6 units "SGD" epochs 100**

Compiling the ANN

In [113]:
ann_2_6_ibm.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [114]:
ann_2_6_ibm.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
33/33 [==============================] - 0s 956us/step - loss: 0.1900 - accuracy: 0.9125
Epoch 2/100
33/33 [==============================] - 0s 1ms/step - loss: 0.1890 - accuracy: 0.9116
Epoch 3/100
33/33 [==============================] - 0s 1ms/step - loss: 0.1891 - accuracy: 0.9193
Epoch 4/100
33/33 [==============================] - 0s 1ms/step - loss: 0.1885 - accuracy: 0.9135
Epoch 5/100
33/33 [==============================] - 0s 1ms/step - loss: 0.1885 - accuracy: 0.9135
Epoch 6/100
33/33 [==============================] - 0s 1ms/step - loss: 0.1892 - accuracy: 0.9116
Epoch 7/100
33/33 [==============================] - 0s 950us/step - loss: 0.1880 - accuracy: 0.9164
Epoch 8/100
33/33 [==============================] - 0s 1ms/step - loss: 0.1878 - accuracy: 0.9164
Epoch 9/100
33/33 [==============================] - 0s 919us/step - loss: 0.1886 - accuracy: 0.9145
Epoch 10/100
33/33 [==============================] - 0s 913us/step - loss: 0.1871 - accuracy: 0.9184
E

Training set results and Confusion Matrix

In [115]:
y_pred_in = ann_2_6_ibm.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[851  19]
 [ 49 110]]
Accuracy: 93.39 %


Test set Predition & Confusion Matrix

In [116]:
y_pred = ann_2_6_ibm.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[326  48]
 [ 56  11]]
Accuracy: 76.42 %


#### **ANN 2 hidden layers 6 units "SGD" epochs 300**

Training the Training set

In [117]:
ann_2_6_ibm.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
33/33 [==============================] - 0s 1ms/step - loss: 0.1750 - accuracy: 0.9281
Epoch 2/300
33/33 [==============================] - 0s 912us/step - loss: 0.1753 - accuracy: 0.9271
Epoch 3/300
33/33 [==============================] - 0s 920us/step - loss: 0.1745 - accuracy: 0.9242
Epoch 4/300
33/33 [==============================] - 0s 1ms/step - loss: 0.1755 - accuracy: 0.9281
Epoch 5/300
33/33 [==============================] - 0s 1ms/step - loss: 0.1743 - accuracy: 0.9261
Epoch 6/300
33/33 [==============================] - 0s 1ms/step - loss: 0.1741 - accuracy: 0.9252
Epoch 7/300
33/33 [==============================] - 0s 929us/step - loss: 0.1745 - accuracy: 0.9252
Epoch 8/300
33/33 [==============================] - 0s 980us/step - loss: 0.1738 - accuracy: 0.9271
Epoch 9/300
33/33 [==============================] - 0s 1ms/step - loss: 0.1739 - accuracy: 0.9281
Epoch 10/300
33/33 [==============================] - 0s 940us/step - loss: 0.1750 - accuracy: 0.9232

Training set results and Confusion Matrix

In [118]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_6_ibm.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[853  17]
 [ 43 116]]
Accuracy: 94.17 %


Test set Predition & Confusion Matrix

In [119]:
y_pred = ann_2_6_ibm.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[319  55]
 [ 57  10]]
Accuracy: 74.60 %


#### **ANN 2 hidden layers 4 units "Adam" epochs 100**

Compiling the ANN

In [120]:
ann_2_4_ibm.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [121]:
ann_2_4_ibm.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
33/33 [==============================] - 0s 1ms/step - loss: 0.7714 - accuracy: 0.4568
Epoch 2/100
33/33 [==============================] - 0s 1ms/step - loss: 0.6915 - accuracy: 0.5627
Epoch 3/100
33/33 [==============================] - 0s 1ms/step - loss: 0.6392 - accuracy: 0.6589
Epoch 4/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5992 - accuracy: 0.7386
Epoch 5/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5714 - accuracy: 0.7707
Epoch 6/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5505 - accuracy: 0.8076
Epoch 7/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5344 - accuracy: 0.8280
Epoch 8/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5209 - accuracy: 0.8397
Epoch 9/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5101 - accuracy: 0.8406
Epoch 10/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5011 - accuracy: 0.8426
Epoch 11/

Training set results and Confusion Matrix

In [122]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_4_ibm.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[867   3]
 [157   2]]
Accuracy: 84.45 %


Test set Predition & Confusion Matrix

In [123]:
y_pred = ann_2_4_ibm.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[369   5]
 [ 67   0]]
Accuracy: 83.67 %


#### **ANN 2 hidden layers 4 units "Adam" epochs 300**

Training the Training set

In [124]:
ann_2_4_ibm.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3648 - accuracy: 0.8455
Epoch 2/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3644 - accuracy: 0.8455
Epoch 3/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3631 - accuracy: 0.8455
Epoch 4/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3630 - accuracy: 0.8445
Epoch 5/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3623 - accuracy: 0.8455
Epoch 6/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3620 - accuracy: 0.8445
Epoch 7/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3610 - accuracy: 0.8445
Epoch 8/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3603 - accuracy: 0.8455
Epoch 9/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3600 - accuracy: 0.8455
Epoch 10/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3596 - accuracy: 0.8455
Epoch 11/

Training set results and Confusion Matrix

In [125]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_4_ibm.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[860  10]
 [124  35]]
Accuracy: 86.98 %


Test set Predition & Confusion Matrix

In [126]:
y_pred = ann_2_4_ibm.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[355  19]
 [ 65   2]]
Accuracy: 80.95 %


#### **ANN 2 hidden layers 4 units "SGD" epochs 100**

Compiling the ANN

In [127]:
ann_2_4_ibm.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [128]:
ann_2_4_ibm.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2986 - accuracy: 0.8688
Epoch 2/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2993 - accuracy: 0.8688
Epoch 3/100
33/33 [==============================] - 0s 992us/step - loss: 0.2988 - accuracy: 0.8678
Epoch 4/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2989 - accuracy: 0.8669
Epoch 5/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2983 - accuracy: 0.8707
Epoch 6/100
33/33 [==============================] - 0s 976us/step - loss: 0.2986 - accuracy: 0.8678
Epoch 7/100
33/33 [==============================] - 0s 995us/step - loss: 0.2987 - accuracy: 0.8678
Epoch 8/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2991 - accuracy: 0.8669
Epoch 9/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2986 - accuracy: 0.8669
Epoch 10/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2979 - accuracy: 0.8659
Epo

Training set results and Confusion Matrix

In [129]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_4_ibm.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[841  29]
 [102  57]]
Accuracy: 87.27 %


Test set Predition & Confusion Matrix

In [130]:
y_pred = ann_2_4_ibm.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[334  40]
 [ 59   8]]
Accuracy: 77.55 %


#### **ANN 2 hidden layers 4 units "SGD" epochs 300**

Training the Training set

In [131]:
ann_2_4_ibm.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2942 - accuracy: 0.8727
Epoch 2/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2949 - accuracy: 0.8707
Epoch 3/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2941 - accuracy: 0.8717
Epoch 4/300
33/33 [==============================] - 0s 982us/step - loss: 0.2953 - accuracy: 0.8737
Epoch 5/300
33/33 [==============================] - 0s 966us/step - loss: 0.2946 - accuracy: 0.8717
Epoch 6/300
33/33 [==============================] - 0s 929us/step - loss: 0.2958 - accuracy: 0.8727
Epoch 7/300
33/33 [==============================] - 0s 885us/step - loss: 0.2938 - accuracy: 0.8727
Epoch 8/300
33/33 [==============================] - 0s 926us/step - loss: 0.2946 - accuracy: 0.8727
Epoch 9/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2945 - accuracy: 0.8669
Epoch 10/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2935 - accuracy: 0.8707

Training set results and Confusion Matrix

In [132]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_2_4_ibm.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[843  27]
 [ 98  61]]
Accuracy: 87.85 %


Test set Predition & Confusion Matrix

In [133]:
y_pred = ann_2_4_ibm.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[337  37]
 [ 60   7]]
Accuracy: 78.00 %


### **Building the Ann with 1 hidden layers, 4 & 6 Units, 100 & 300 epochs**

 **Initializing the ANN
(1 hidden layer, 6 unite, activation='relu', output activation='sigmoid')**

In [134]:
ann_1_6 = tf.keras.models.Sequential()
ann_1_6.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann_1_6.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

(2 hidden layer, 4 unite, activation='relu', output activation='sigmoid')

In [135]:
ann_1_4 = tf.keras.models.Sequential()
ann_1_4.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann_1_4.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#### **ANN 1 hidden layers 6 units "Adam" epochs 100**

Compiling the ANN

In [136]:
ann_1_6.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [137]:
ann_1_6.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5786 - accuracy: 0.7357
Epoch 2/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5373 - accuracy: 0.7891
Epoch 3/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5094 - accuracy: 0.8241
Epoch 4/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4881 - accuracy: 0.8435
Epoch 5/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4728 - accuracy: 0.8426
Epoch 6/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4600 - accuracy: 0.8445
Epoch 7/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4510 - accuracy: 0.8445
Epoch 8/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4435 - accuracy: 0.8455
Epoch 9/100
33/33 [==============================] - 0s 982us/step - loss: 0.4374 - accuracy: 0.8455
Epoch 10/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4317 - accuracy: 0.8455
Epoch 1

Training set results and Confusion Matrix

In [138]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[865   5]
 [138  21]]
Accuracy: 86.10 %


Test set Predition & Confusion Matrix

In [139]:
y_pred = ann_1_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[360  14]
 [ 65   2]]
Accuracy: 82.09 %


#### **ANN 1 hidden layers 6 units "Adam" epochs 300**

Training the Training set

In [140]:
ann_1_6.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8620
Epoch 2/300
33/33 [==============================] - 0s 950us/step - loss: 0.3324 - accuracy: 0.8610
Epoch 3/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8610
Epoch 4/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8581
Epoch 5/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8581
Epoch 6/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3309 - accuracy: 0.8610
Epoch 7/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3302 - accuracy: 0.8610
Epoch 8/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8601
Epoch 9/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8620
Epoch 10/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.8620
Epoch 1

Training set results and Confusion Matrix

In [141]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[852  18]
 [ 83  76]]
Accuracy: 90.18 %


Test set Predition & Confusion Matrix

In [142]:
y_pred = ann_1_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[328  46]
 [ 56  11]]
Accuracy: 76.87 %


#### **ANN 1 hidden layers 6 units "SGD" epochs 100**

Compiling the ANN

In [143]:
ann_1_6.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [144]:
ann_1_6.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
33/33 [==============================] - 0s 985us/step - loss: 0.2524 - accuracy: 0.9009
Epoch 2/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2521 - accuracy: 0.8980
Epoch 3/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2519 - accuracy: 0.8999
Epoch 4/100
33/33 [==============================] - 0s 1ms/step - loss: 0.2519 - accuracy: 0.8960
Epoch 5/100
33/33 [==============================] - 0s 996us/step - loss: 0.2519 - accuracy: 0.8999
Epoch 6/100
33/33 [==============================] - 0s 880us/step - loss: 0.2518 - accuracy: 0.8970
Epoch 7/100
33/33 [==============================] - 0s 882us/step - loss: 0.2517 - accuracy: 0.9009
Epoch 8/100
33/33 [==============================] - 0s 863us/step - loss: 0.2513 - accuracy: 0.8970
Epoch 9/100
33/33 [==============================] - 0s 872us/step - loss: 0.2518 - accuracy: 0.8970
Epoch 10/100
33/33 [==============================] - 0s 909us/step - loss: 0.2513 - accuracy: 0.

Training set results and Confusion Matrix

In [145]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[851  19]
 [ 84  75]]
Accuracy: 89.99 %


Test set Predition & Confusion Matrix

In [146]:
y_pred = ann_1_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[327  47]
 [ 54  13]]
Accuracy: 77.10 %


#### **ANN 1 hidden layers 6 units "SGD" epochs 300**

Training the Training set

In [147]:
ann_1_6.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2469 - accuracy: 0.9009
Epoch 2/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2469 - accuracy: 0.8999
Epoch 3/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2469 - accuracy: 0.8999
Epoch 4/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2468 - accuracy: 0.8980
Epoch 5/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2470 - accuracy: 0.9009
Epoch 6/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2469 - accuracy: 0.8999
Epoch 7/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2469 - accuracy: 0.8989
Epoch 8/300
33/33 [==============================] - 0s 1ms/step - loss: 0.2477 - accuracy: 0.8989
Epoch 9/300
33/33 [==============================] - 0s 928us/step - loss: 0.2473 - accuracy: 0.8980
Epoch 10/300
33/33 [==============================] - 0s 938us/step - loss: 0.2468 - accuracy: 0.8980
Epoch

Training set results and Confusion Matrix

In [148]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_6.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[846  24]
 [ 70  89]]
Accuracy: 90.86 %


Test set Predition & Confusion Matrix

In [149]:
y_pred = ann_1_6.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[322  52]
 [ 55  12]]
Accuracy: 75.74 %


#### **ANN 1 hidden layers 4 units "Adam" epochs 100**

Compiling the ANN

In [150]:
ann_1_4.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [151]:
ann_1_4.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
33/33 [==============================] - 0s 1ms/step - loss: 0.6924 - accuracy: 0.6521
Epoch 2/100
33/33 [==============================] - 0s 1ms/step - loss: 0.6343 - accuracy: 0.7036
Epoch 3/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5902 - accuracy: 0.7464
Epoch 4/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5546 - accuracy: 0.7881
Epoch 5/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5259 - accuracy: 0.8095
Epoch 6/100
33/33 [==============================] - 0s 1ms/step - loss: 0.5041 - accuracy: 0.8299
Epoch 7/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4876 - accuracy: 0.8377
Epoch 8/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4744 - accuracy: 0.8367
Epoch 9/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4630 - accuracy: 0.8406
Epoch 10/100
33/33 [==============================] - 0s 1ms/step - loss: 0.4547 - accuracy: 0.8426
Epoch 11/

Training set results and Confusion Matrix

In [152]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[866   4]
 [149  10]]
Accuracy: 85.13 %


Test set Predition & Confusion Matrix

In [153]:
y_pred = ann_1_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[360  14]
 [ 65   2]]
Accuracy: 82.09 %


#### **ANN 1 hidden layers 4 units "Adam" epochs 300**

Training the Training set

In [154]:
ann_1_4.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3605 - accuracy: 0.8513
Epoch 2/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3601 - accuracy: 0.8503
Epoch 3/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3594 - accuracy: 0.8503
Epoch 4/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3595 - accuracy: 0.8503
Epoch 5/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3588 - accuracy: 0.8503
Epoch 6/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3582 - accuracy: 0.8523
Epoch 7/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3580 - accuracy: 0.8513
Epoch 8/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3578 - accuracy: 0.8523
Epoch 9/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3572 - accuracy: 0.8533
Epoch 10/300
33/33 [==============================] - 0s 994us/step - loss: 0.3563 - accuracy: 0.8542
Epoch 1

Training set results and Confusion Matrix

In [155]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[847  23]
 [110  49]]
Accuracy: 87.07 %


Test set Predition & Confusion Matrix

In [156]:
y_pred = ann_1_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[337  37]
 [ 62   5]]
Accuracy: 77.55 %


#### **ANN 1 hidden layers 4 units "SGD" epochs 100**

Compiling the ANN

In [157]:
ann_1_4.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the Training set

In [158]:
ann_1_4.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
33/33 [==============================] - 0s 1ms/step - loss: 0.3043 - accuracy: 0.8707
Epoch 2/100
33/33 [==============================] - 0s 918us/step - loss: 0.3042 - accuracy: 0.8717
Epoch 3/100
33/33 [==============================] - 0s 894us/step - loss: 0.3042 - accuracy: 0.8688
Epoch 4/100
33/33 [==============================] - 0s 878us/step - loss: 0.3040 - accuracy: 0.8707
Epoch 5/100
33/33 [==============================] - 0s 915us/step - loss: 0.3042 - accuracy: 0.8707
Epoch 6/100
33/33 [==============================] - 0s 905us/step - loss: 0.3041 - accuracy: 0.8707
Epoch 7/100
33/33 [==============================] - 0s 938us/step - loss: 0.3041 - accuracy: 0.8678
Epoch 8/100
33/33 [==============================] - 0s 961us/step - loss: 0.3041 - accuracy: 0.8698
Epoch 9/100
33/33 [==============================] - 0s 1ms/step - loss: 0.3038 - accuracy: 0.8698
Epoch 10/100
33/33 [==============================] - 0s 955us/step - loss: 0.3039 - accuracy: 

Training set results and Confusion Matrix

In [159]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[846  24]
 [106  53]]
Accuracy: 87.37 %


Test set Predition & Confusion Matrix

In [160]:
y_pred = ann_1_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[333  41]
 [ 62   5]]
Accuracy: 76.64 %


#### **ANN 1 hidden layers 4 units "SGD" epochs 300**

Training the Training set

In [161]:
ann_1_4.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3015 - accuracy: 0.8727
Epoch 2/300
33/33 [==============================] - 0s 914us/step - loss: 0.3013 - accuracy: 0.8707
Epoch 3/300
33/33 [==============================] - 0s 893us/step - loss: 0.3015 - accuracy: 0.8717
Epoch 4/300
33/33 [==============================] - 0s 961us/step - loss: 0.3012 - accuracy: 0.8678
Epoch 5/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3014 - accuracy: 0.8717
Epoch 6/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3012 - accuracy: 0.8727
Epoch 7/300
33/33 [==============================] - 0s 951us/step - loss: 0.3015 - accuracy: 0.8678
Epoch 8/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3012 - accuracy: 0.8707
Epoch 9/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3013 - accuracy: 0.8707
Epoch 10/300
33/33 [==============================] - 0s 1ms/step - loss: 0.3012 - accuracy: 0.8707
E

Training set results and Confusion Matrix

In [162]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_in = ann_1_4.predict(X_train)
y_pred_in = (y_pred_in > 0.5)
cm = confusion_matrix(y_train, y_pred_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_train, y_pred_in)*100))

[[842  28]
 [ 96  63]]
Accuracy: 87.95 %


Test set Predition & Confusion Matrix

In [163]:
y_pred = ann_1_4.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[328  46]
 [ 63   4]]
Accuracy: 75.28 %


##**K Nearest Neighbors**

### **3 neighbors & metric = 'minkowski'**

In [164]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [165]:
y_pred_K_in = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred_K_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred_K_in)*100))

[[347  27]
 [ 61   6]]
Accuracy: 80.05 %


In [166]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 80.08 %
Standard Deviation: 1.56 %


In [167]:
y_pred_K = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Standard Deviation: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[328  46]
 [ 63   4]]
Standard Deviation: 75.28 %


### **10 neighbors & metric = 'minkowski'**

In [168]:
classifier = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [169]:
y_pred_K_in = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred_K_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred_K_in)*100))

[[373   1]
 [ 67   0]]
Accuracy: 84.58 %


In [170]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 84.45 %
Standard Deviation: 0.40 %


In [171]:
y_pred_K = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Standard Deviation: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[328  46]
 [ 63   4]]
Standard Deviation: 75.28 %


### **3 neighbors & metric = 'euclidean'**

In [172]:
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [173]:
y_pred_K_in = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred_K_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred_K_in)*100))

[[347  27]
 [ 61   6]]
Accuracy: 80.05 %


In [174]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 80.08 %
Standard Deviation: 1.56 %


In [175]:
y_pred_K = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Standard Deviation: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[328  46]
 [ 63   4]]
Standard Deviation: 75.28 %


### **10 neighbors & metric = 'euclidean'**

In [176]:
classifier = KNeighborsClassifier(n_neighbors = 10, metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [177]:
y_pred_K_in = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred_K_in)
print(cm)
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred_K_in)*100))

[[373   1]
 [ 67   0]]
Accuracy: 84.58 %


In [178]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 84.45 %
Standard Deviation: 0.40 %


In [179]:
y_pred_K = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Standard Deviation: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[328  46]
 [ 63   4]]
Standard Deviation: 75.28 %
